name: "tugas_akhir"
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  backendless_sdk: ^7.2.3
  flutter_launcher_icons: ^0.11.0

  cupertino_icons: ^1.0.5
  webview_flutter: ^3.0.4
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  carousel_slider: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets: 
  - assets/
