name: MannaGo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  backendless_sdk: 7.2.3
  flutter_launcher_icons: 0.11.0
  cupertino_icons: 1.0.5
  webview_flutter: 4.0.1
  shared_preferences: 2.0.15
  intl: 0.18.0
  carousel_slider: 4.2.0
  flutter_expandable_fab: 1.6.1
  email_validator: 2.1.17
  flutter_slidable: 2.0.0
  firebase_core: 2.4.0
  firebase_messaging: 14.2.0
  upgrader: 5.0.0
  flutter_screenutil: 5.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets: 
  - assets/

flutter_icons:
  image_path_android: "assets/android/play_store_512.png"
  android: true
